# Generated by Django 4.0.5 on 2022-07-02 20:06

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=350)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='Heavens_photo/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Video', embed_video.fields.EmbedVideoField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
