# Generated by Django 4.0.5 on 2022-07-07 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
