# Generated by Django 4.0.5 on 2022-07-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0004_category_contibute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contibute',
            name='categories',
        ),
        migrations.AddField(
            model_name='contibute',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Partner.category'),
        ),
    ]
