# Generated by Django 4.0.5 on 2022-07-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0005_remove_contibute_categories_contibute_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contibute',
            new_name='Contribute',
        ),
    ]
